/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JButton;

/**
 *
 * @author Gaspar
 */
public class UICasinha extends JButton {
    private int posicao_array;
    private Color corPiao;
    public UICasinha() {
        this.posicao_array = -1;
        setPreferredSize(new Dimension(50, 50));
        setBackground(Color.WHITE);
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (corPiao != null) {
            Graphics2D g2d = (Graphics2D) g.create();
            g2d.setColor(corPiao);
            g2d.fillOval(10, 10, 30, 30);
            g2d.dispose();
        }
    }

    public Color getCorPiao() {
        return corPiao;
    }

    public void setCorPiao(Color corPiao) {
        this.corPiao = corPiao;
    }

    public int getPosicao_array() {
        return posicao_array;
    }

    public void setPosicao_array(int posicao_array) {
        this.posicao_array = posicao_array;
    }
    
    public void setCor(Color cor) {
        setBackground(cor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
